# Rename this file to file to secrets.toml

[cloud]
provider = "s3"
s3_bucket_name = "your-bucket-name"
s3_key_prefix = "expense-tracker"   # optional

# AWS credentials (only needed if not using IAM roles or ~/.aws/credentials)
# [aws]
# aws_access_key_id = "..."
# aws_secret_access_key = "..."
# aws_default_region = "us-east-1"
